PUBLIC_QUOTA_MODE_DAILY_GLOBAL = "daily_global"
PUBLIC_QUOTA_MODE_PER_IP = "per_ip"
PUBLIC_QUOTA_MODES = {PUBLIC_QUOTA_MODE_DAILY_GLOBAL, PUBLIC_QUOTA_MODE_PER_IP}

PUBLIC_QUOTA_FEATURE_IMAGE = "image"
PUBLIC_QUOTA_FEATURE_COMIC = "comic"
PUBLIC_QUOTA_FEATURE_APP = "app"
PUBLIC_QUOTA_FEATURES = {
    PUBLIC_QUOTA_FEATURE_IMAGE,
    PUBLIC_QUOTA_FEATURE_COMIC,
    PUBLIC_QUOTA_FEATURE_APP,
}

PUBLIC_QUOTA_TIMEZONE = "Asia/Shanghai"
DEFAULT_PUBLIC_QUOTA_MODE = PUBLIC_QUOTA_MODE_DAILY_GLOBAL
DEFAULT_PUBLIC_QUOTA_DAILY_GLOBAL_LIMIT = 20
DEFAULT_PUBLIC_QUOTA_PER_IP_LIMIT = 20
