PROJECT_STATUS_DRAFT = "draft"

TASK_TYPE_IMPORT = "import"
TASK_TYPE_SCRIPT_GENERATE = "script-generate"
TASK_TYPE_SCENE_RENDER = "scene-render"
TASK_TYPE_CHAPTER_RENDER_BATCH = "chapter-render-batch"

TASK_STATUS_PENDING = "pending"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"

TASK_TYPES = {
    TASK_TYPE_IMPORT,
    TASK_TYPE_SCRIPT_GENERATE,
    TASK_TYPE_SCENE_RENDER,
    TASK_TYPE_CHAPTER_RENDER_BATCH,
}

TASK_STATUSES = {
    TASK_STATUS_PENDING,
    TASK_STATUS_RUNNING,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
}
